import Link from "next/link";
import { notFound } from "next/navigation";
import styles from "./journey.module.css";

type Journey = { title:string; place:string; type:string; duration:string; price:string; image:string; intro:string; story:string; highlights:string[]; itinerary:{time:string; title:string; copy:string}[]; gallery:string[]; included:string[]; };
const local=(name:string)=>`${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/assets/${name}`;
const pexels={ safari:"https://images.pexels.com/photos/36298878/pexels-photo-36298878.jpeg?auto=compress&cs=tinysrgb&w=1600", coast:"https://images.pexels.com/photos/2041928/pexels-photo-2041928.jpeg?auto=compress&cs=tinysrgb&w=1600" };
const baseItinerary=[{time:"Before you travel",title:"A personal confirmation",copy:"You receive a clear plan, packing guidance and direct support from our team."},{time:"On the day",title:"Move at a human pace",copy:"Your host or guide welcomes you into the experience, with room for conversation and unexpected moments."},{time:"After",title:"Leave with context",copy:"We share practical follow-up notes so the stories and places you encountered stay with you."}];
const j=(title:string,place:string,type:string,duration:string,price:string,image:string,intro:string,story:string,highlights:string[],gallery:string[],included:string[]):Journey=>({title,place,type,duration,price,image,intro,story,highlights,gallery,included,itinerary:baseItinerary});
const journeys:Record<string,Journey>={
 "kokwet-to-crown":j("Kokwet to Crown","Nandi Hills","Living heritage","Full day","From $260",local("traditional-homestead.jpeg"),"A generous welcome into Nandi life, shaped by the people who live and remember it.","This is not a display of culture. It is a day of exchange: food made and shared, family stories, the work of local makers and the rhythms of a place known from the inside.",["Hosted cultural exchange","Traditional food & shared table","Stories, dance & craft","Transport, lunch & photos"],[local("nandi-cultural-collection.jpeg"),local("heritage-objects.jpeg"),local("historic-shield.jpeg")],["Local host and guide","Return transport from agreed pickup","Shared meal and refreshments","Entry, activities and photography"]),
 "the-kitchen-table":j("The Kitchen Table","Western Kenya","Food & story","Half day","Enquire",local("heritage-gathering-space.jpeg"),"Start with a meal and discover how ingredients, memory and hospitality hold a place together.","Every recipe carries a route: from the field to the kitchen, from one generation to the next. This small-group experience follows that route through making, tasting and conversation.",["Market-to-table stories","Seasonal cooking session","Shared meal","Meet local makers"],[local("heritage-gathering-space.jpeg"),local("culture-walk.jpeg"),local("heritage-gallery.jpeg")],["Host-led cooking and tasting","Shared meal","Ingredient notes","Local transfers when included in your plan"]),
 "mara-in-two-days":j("Mara in 2 Days","Maasai Mara","Wild landscapes","2 days · 1 night","From $420",pexels.safari,"A short safari with the time and care to feel the scale of the Mara.","We make the most of two days without turning them into a race. Expect dawn light, a thoughtful guide, a tented night and long pauses for the animals and the landscape to set the pace.",["Two guided game drives","Tented camp stay","Park-ready itinerary","Small-group departure"],[pexels.safari,local("landscape-trail.jpeg"),local("forest-memorial.jpeg")],["Professional safari guide","Transport from agreed pickup","One night accommodation","Meals as stated in your confirmation"]),
 "objects-and-origins":j("Objects & Origins","Nandi Hills","Heritage walk","2 hours","Enquire",local("nandi-cultural-collection.jpeg"),"An intimate, object-led introduction to the histories that endure in Nandi Hills.","Through tools, adornment, shields and oral memory, this gentle walk opens a conversation about what objects can carry—and why the people connected to them should lead the telling.",["Object-led storytelling","Small group format","Hosted heritage walk","Ideal Nandi add-on"],[local("nandi-cultural-collection.jpeg"),local("heritage-objects.jpeg"),local("cultural-artefact-detail.jpeg")],["Local heritage host","Entry and interpretation","Tea or refreshment","Optional connection to a longer itinerary"]),
 "cultures-of-kenya":j("Cultures of Kenya","Across Kenya","Upcoming series","New routes 2026","Join the list",local("forest-memorial.jpeg"),"A growing collection of community-led journeys across Kenya.","We are developing this series in conversation with local hosts, makers and culture bearers. Each route will be introduced only when it is ready to offer a respectful, reciprocal experience.",["Community-led development","Small-group journeys","Food, craft & memory","New hosts announced carefully"],[local("forest-memorial.jpeg"),local("culture-walk.jpeg"),local("cultural-site-portrait.jpeg")],["Early itinerary access","Priority launch updates","Host-led experience design","Clear, responsible travel guidance"]),
 "fly-nandi-hills":j("Fly Nandi Hills","Nandi Hills","Sky & land","Coming December 2026","Waitlist",local("nandi-view-panorama.jpeg"),"A new way to understand the highlands: from above, then back on the ground.","The flight is only one part of the story. We are shaping a half-day that pairs valley views with tea-country context, local encounters and a considered return to earth.",["Paragliding flight experience","Tea-country perspective","Photo & video keepsake","Launching December 2026"],[local("nandi-view-panorama.jpeg"),local("landscape-trail.jpeg"),local("nandi-garden-pond.jpeg")],["Waitlist priority","Launch updates","Planned transport options","Detailed safety information before booking"]),
 "mara-nakuru-amboseli":j("Three Parks, One Story","Mara · Nakuru · Amboseli","Classic safari","6 days","Tailored quote",pexels.safari,"A generous Kenya circuit linking big cats, flamingo shores and elephant country.","Designed as a balanced, unhurried route through three remarkable ecosystems, with enough time to let every place have its own character.",["Maasai Mara game drives","Lake Nakuru birdlife","Amboseli elephant country","Tailored accommodation level"],[pexels.safari,local("landscape-trail.jpeg"),pexels.coast],["Private or small-group transport","Guided game drives","Accommodation options","Custom quote and pre-trip support"]),
 "migration-season":j("Migration Season","Maasai Mara","Seasonal safari","3 days","Tailored quote",pexels.safari,"Follow the changing rhythms of the Mara in a carefully timed seasonal escape.","We build the route around the conditions on the ground, your preferred comfort level and the value of being in the right place at the right pace.",["Season-aware planning","Guided game drives","Flexible camp options","Departure support"],[pexels.safari,local("landscape-trail.jpeg"),local("forest-memorial.jpeg")],["Expert itinerary planning","Guide and vehicle","Accommodation guidance","Pre-departure briefing"]),
 "nairobi-day-out":j("Nairobi, Up Close","Nairobi","City & culture","Full day","From $150",local("culture-walk.jpeg"),"A city day that links wildlife, art, food and the layered histories of Kenya’s capital.","Instead of ticking off attractions, we help you choose a city rhythm that fits: a museum conversation, a local table, a conservation stop or an architecture walk.",["Flexible city route","Museum & culture options","Wildlife add-ons","Private guide available"],[local("culture-walk.jpeg"),local("heritage-gallery.jpeg"),local("nandi-garden-pond.jpeg")],["Private guide","Tailored pickup","Entry planning","Food stop recommendations"]),
 "mount-kenya-trek":j("Mount Kenya, On Foot","Mount Kenya","Mountain journey","5 days","Tailored quote",pexels.safari,"A mountain itinerary designed around acclimatisation, care and the joy of walking well.","The mountain asks for patience. We work with experienced teams to build a route that respects your pace, the weather and the landscapes you came to meet.",["Route matched to experience","Acclimatisation-focused plan","Mountain crew support","Optional cultural extension"],[pexels.safari,local("landscape-trail.jpeg"),local("forest-memorial.jpeg")],["Qualified mountain team","Route planning","Accommodation or camping options","Pre-trip kit guidance"]),
 "aberdare-walks":j("Aberdare Walks","Aberdares","Forest & highlands","5 days","Tailored quote",local("forest-memorial.jpeg"),"A quieter Kenya: forest paths, cool air and highland landscapes made for walking.","This is a route for travellers who would rather feel a landscape underfoot. We build in the conditions, safety support and breathing room that a good walking journey needs.",["Guided highland walks","Flexible accommodation","Birding opportunities","Small group format"],[local("forest-memorial.jpeg"),local("landscape-trail.jpeg"),local("nandi-garden-pond.jpeg")],["Route guide","Accommodation plan","Walking safety briefing","Custom transfers"]),
 "lake-naivasha":j("Lake & Rift","Naivasha","Lakeside escape","3 days","Tailored quote",local("nandi-garden-pond.jpeg"),"A gentle Great Rift Valley escape, built around water, birdlife and open horizons.","Lake time shifts the pace. This journey pairs relaxed observation with local context and thoughtful accommodation choices.",["Lakeside stay options","Birding & nature walks","Rift Valley viewpoints","Private or shared departure"],[local("nandi-garden-pond.jpeg"),local("heritage-garden.jpeg"),local("forest-memorial.jpeg")],["Tailored accommodation","Ground transport","Activity planning","Local guide options"]),
 "coastal-escape":j("Indian Ocean Slowdown","Diani · Kilifi · Malindi","Coastal escape","4–6 days","Tailored quote",pexels.coast,"A coast journey that balances beach time with Swahili heritage, food and local rhythm.","Choose your coast: quiet, curious or celebratory. We build the right blend of shoreline, market, old-town story and time to simply be.",["Beach accommodation choices","Swahili heritage add-ons","Ocean activity options","Family and couple friendly"],[pexels.coast,pexels.safari,local("nandi-garden-pond.jpeg")],["Accommodation planning","Airport or rail transfer options","Activity recommendations","Local food experiences"]),
 "tanzania-north":j("Northern Tanzania","Arusha · Serengeti · Ngorongoro","Regional safari","7–10 days","Tailored quote",pexels.safari,"A classic northern circuit, planned with the same care we bring to every journey.","From the Serengeti’s vastness to the drama of the crater, this is a regional safari for travellers who want enough time to let Tanzania unfold.",["Serengeti route options","Ngorongoro crater day","Lake Manyara extension","Cross-border planning"],[pexels.safari,local("landscape-trail.jpeg"),pexels.coast],["Cross-border itinerary support","Guides and transport","Accommodation options","Clear inclusions before confirmation"]),
 "zanzibar-extension":j("Zanzibar Extension","Zanzibar","Island continuation","4 days","Tailored quote",pexels.coast,"An Indian Ocean coda for a safari or cultural journey: salt air, Stone Town stories and time to exhale.","Add a softer final chapter to your East African journey, with a stay tailored to whether you want heritage, beach, food or all three.",["Stone Town options","Beach stay choices","Spice & food experiences","Safari combination planning"],[pexels.coast,local("nandi-garden-pond.jpeg"),local("culture-walk.jpeg")],["Accommodation planning","Airport transfers","Optional guided experiences","Combination-trip support"])
};
export function generateStaticParams(){return Object.keys(journeys).map(slug=>({slug}));}
export default async function JourneyPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=journeys[slug];if(!item)notFound();return <main className={styles.page}><header className={styles.nav}><Link href="/" className={styles.brand}><span>K</span><b>Kokwet<br/><i>to Crown</i></b></Link><Link href="/#journeys">All journeys</Link><a href="#enquire">Plan this journey ↗</a></header><section className={styles.hero} style={{backgroundImage:`linear-gradient(90deg,rgba(11,28,19,.82),rgba(11,28,19,.22)),url('${item.image}')`}}><div><p>{item.type} · {item.place}</p><h1>{item.title}</h1><p className={styles.intro}>{item.intro}</p><div className={styles.meta}><span>{item.duration}</span><span>{item.price}</span></div></div></section><section className={styles.overview}><p className={styles.kicker}>A considered experience</p><div><h2>A journey made<br/>for <em>connection.</em></h2><p>{item.story}</p><ul>{item.highlights.map(x=><li key={x}>✓ {x}</li>)}</ul></div></section><section className={styles.itinerary}><p className={styles.kicker}>How it unfolds</p><h2>The shape of<br/>your journey.</h2><div>{item.itinerary.map(x=><article key={x.time}><b>{x.time}</b><h3>{x.title}</h3><p>{x.copy}</p></article>)}</div></section><section className={styles.gallery}>{item.gallery.map((image,index)=><div key={image+index} style={{backgroundImage:`url('${image}')`}}/>)}</section><section className={styles.details}><div><p className={styles.kicker}>The practical pieces</p><h2>What’s included.</h2></div><ul>{item.included.map(x=><li key={x}>{x}<span>+</span></li>)}</ul></section><section className={styles.enquire} id="enquire"><div><p className={styles.kicker}>Make it yours</p><h2>Ready when<br/>you <em>are.</em></h2><p>Tell us your dates, group size and what you hope to take from this journey. We’ll come back with a clear next step.</p></div><a href={`mailto:info@kokwettocrown.co.ke?subject=Enquiry%20for%20${encodeURIComponent(item.title)}`}>Enquire about {item.title} <span>↗</span></a></section><footer><Link href="/">← Back to all journeys</Link><p>© 2026 Kokwet to Crown Ltd.</p></footer></main>}
